travis:
  secure:
    BINSTAR_TOKEN: o1cbS/tHpZXaGtx/KjSMUuL4WfTGbUDsEQpEooyYlAS0T5ho2a8gMBjyNFM/wIBCOWKbZJMtfcGAj+isEK1jV4KijyNARBiwnkgOqDerTONTBeTek07pwin2/6bcqRsVkh1Agi3IKEKP6nmGOh0cTWZVC1/prVfPSfpQJ+UNTmXaYn1FWeJP8KJ/QaceS3SVUQ3ACyhGaYkPRUmPSPQ9wiwfQC1kSJhoX2B4LI0h4hsFIhDfImMy9ALm7frw+S0OOIhDCIdZGXWYix4pVKWmD7jZK15bOZQ5Xsk+0TYInCqenKIpSt1SwGN9iphBCAStIKZUPuXpRzNGIGJnj+jYs+sW7vEIuwEDniHU/59aSm9Wwp4OzfCKDfRRq8d4pVENdsthVd1nflYzV/YQsTGqIfIw3VZqoNXd5lz9+KyQC4dKzAxaoAWFS8T9LgJt1bTiRYliRmOALRiX6TSvR/Nn66QxLmlBdi71iIfviC4EAbgy3N3r3ZXQXRDxMbOFFO4R3NKBfQS9tTOTDavEG2+ewgAGmT7SCZVDbfOFyHTK6bQ8fA5jpYwu8WqEOj25aYDi8TSrO6QIKzBTewfEdurreb6++fxJe4kiw5OZeqVdf3CefPcv7MsBkzcwR4Flmdi4na2kQ6I6pZg1jBqhpPGxwEwqAVLJhPq26NnPSU/mhKY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
